services:
  postgres:
    image: postgres:15
    container_name: ml_monitoring_db
    environment:
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpassword
      POSTGRES_DB: ml_monitoring
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ml_monitoring_api
    environment:
      DB_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: ml_monitoring_dashboard
    environment:
      DB_HOST: postgres
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  pgdata:
